kind: Service
apiVersion: v1
metadata:
  name: delivery-app-v2
  namespace: v2
  labels:
    app: delivery-app-v2
spec:
  selector:
    app: delivery-app-v2
  ports:
    - name: web
      protocol: TCP
      port: 6005
      targetPort: 6005
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-app-v2
  namespace: v2
  labels:
    app: delivery-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-app-v2
  template:
    metadata:
      labels:
        app: delivery-app-v2
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "deliveryappv2"
        dapr.io/app-port: "6005"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: delivery-app-v2
          image: lak9348/dapr-delivery-v2:v0.1.10
          ports:
            - containerPort: 6005
          imagePullPolicy: Always