kind: Service
apiVersion: v1
metadata:
  name: order-app-v2
  namespace: v2
  labels:
    app: order-app-v2
spec:
  selector:
    app: order-app-v2
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app-v2
  namespace: v2
  labels:
    app: order-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app-v2
  template:
    metadata:
      labels:
        app: order-app-v2
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orderappv2"
        dapr.io/app-port: "8080"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: order-app-v2
          image: lak9348/dapr-order-v2:v0.1.13
          ports:
            - containerPort: 8080
          imagePullPolicy: Always