apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: redis-outbox
  namespace: dapr
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis-master.dapr.svc.cluster.local:6379
    - name: redisPassword
      secretKeyRef:
        name: redis
        key: redis-password
    - name: outboxPublishPubsub # Required
      value: "pubsub"
    - name: outboxPublishTopic # Required
      value: "orders"