kind: Service
apiVersion: v1
metadata:
  name: delivery-app-v1
  namespace: v1
  labels:
    app: delivery-app-v1
spec:
  selector:
    app: delivery-app-v1
  ports:
    - protocol: TCP
      port: 6005
      targetPort: 6005
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-app-v1
  namespace: v1
  labels:
    app: delivery-app-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-app-v1
  template:
    metadata:
      labels:
        app: delivery-app-v1
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "deliveryappv1"
        dapr.io/app-port: "6005"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: delivery-app-v1
          image: lak9348/dapr-delivery-v1:v0.2.1
          ports:
            - containerPort: 6005
          imagePullPolicy: Always