kind: Service
apiVersion: v1
metadata:
  name: order-app1
  namespace: v1
  labels:
    app: order-app
spec:
  selector:
    app: order-app1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app1
  namespace: v1
  labels:
    app: order-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app1
  template:
    metadata:
      labels:
        app: order-app1
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orderapp1"
        dapr.io/app-port: "8080"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: order-app
          image: lak9348/dapr-order-v1:v0.1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always