kind: Service
apiVersion: v1
metadata:
  name: sub-app
  namespace: dapr
  labels:
    app: sub-app
spec:
  selector:
    app: sub-app
  ports:
    - protocol: TCP
      port: 6005
      targetPort: 6005
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sub-app
  namespace: dapr
  labels:
    app: sub-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sub-app
  template:
    metadata:
      labels:
        app: sub-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "subapp"
        dapr.io/app-port: "6005"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: sub-app
          image: lak9348/dapr-sub:v0.0.1
          ports:
            - containerPort: 6005
          imagePullPolicy: Always