apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  strategy: {}
  template:
    metadata:
      annotations:
        dapr.io/app-id: subscriber
        dapr.io/app-port: "6005"
        dapr.io/config: appconfig
        dapr.io/enabled: "true"
        dapr.io/metrics-port: "60612"
        dapr.io/unix-domain-socket-path: ""
      creationTimestamp: null
      labels:
        app: subscriber
    spec:
      containers:
      - env:
        - name: APP_ID
          value: subscriber
        - name: APP_CHANNEL_ADDRESS
        - name: APP_PORT
          value: "6005"
        - name: DAPR_METRICS_PORT
          value: "60612"
        imagePullPolicy: Always
        name: subscriber
        ports:
        - containerPort: 6005
        resources: {}
